---
title: "Project Göç Dinamikleri"

format:
  html:
    code-fold: true
    code-summary: "Show the code"
    toc: true             
    toc-location: right   
    number-sections: true
    theme: cosmo        
    embed-resources: true
  pdf:
    colorlinks: true
    papersize: a4
    fontsize: 11pt
    margin-left: 2cm
    margin-right: 2cm
    margin-top: 2cm
    margin-bottom: 2cm
---

Welcome to our project page.

Our Team:

Selin DÜZEN
Burcu BARIŞ

Keep an eye on this space to stay updated with my project activities.

# 1. Project Overview and Scope

Göç, yalnızca bireylerin coğrafi yer değiştirmesi değil; ekonomik arayışların, sosyal imkanların ve yapısal kalitenin bir bölgedeki izdüşümüdür. Türkiye’de iller arasındaki gelişmişlik ve yaşam standartları farkı, iç göç hareketlerinin en birincil dinamiklerinden birini oluşturmaktadır.
Bu projede, TÜİK verilerini kullanarak Türkiye'nin 81 ilinin Net Göç (Net Göç = Göç Alan - Göç Veren) rakamları ile İllerde Yaşam Endeksi (Yaşanabilirlik) göstergeleri arasındaki çok boyutlu ilişkiyi analitik yöntemlerle incelemeyi hedefliyoruz. Amacımız, insanların hangi yaşamsal faktörler (ekonomi, eğitim, sağlık, çevre kalitesi, güvenlik vb.) nedeniyle mevcut şehirlerini terk ettiğini veya belirli şehirlere yöneldiğini veri analitiği ve istatistiksel modellerle ortaya koymaktır. Bu çalışma, bölgesel kalkınma politikaları ve kentsel planlama kararları için veri odaklı bir projeksiyon sunması açısından kritik bir karar destek mekanizması niteliğindedir.
Projenin Temel Amaçları
Göç Profillerinin Çıkarılması: Türkiye'deki "Net Göç Şampiyonları" (en çok net göç alan) ve "Göç Kaynakları" (en çok net göç veren) illeri tespit etmek ve bunları coğrafi olarak haritalandırmak.
Yaşanabilirlik Boyutlarının Etkisi: Yaşam endeksini oluşturan alt kırılımlardan (Gelir ve Servet, Sağlık, Eğitim, Çevre, Güvenlik vb.) hangilerinin göç kararı üzerinde daha baskın birer "itici" veya "çekici" güç olduğunu istatistiksel olarak kanıtlamak.
Kümeleme (Clustering): İlleri hem göç davranışlarına hem de yaşanabilirlik skorlarına göre homojen gruplara ayırarak benzer sosyo-ekonomik dinamiklere sahip şehir yapılarını keşfetmek.


# 2. Data

xxxxxx

#veri seti, veri kümenizi açıklayın. Herhangi bir tam analiz yapmanız veya sonuç çıkarmanız gerekmemekle birlikte, verilere kapsamlı bir genel bakış sunmayı hedefleyin—sütunların ne anlama geldiğini, değerlerin nasıl dağıldığını açıklayın ve potansiyel analizler hakkında fikirlerinizi paylaşın. Özlü tutun, bazı grafikler ekleyebilirsiniz.


1. İllerin yıllara sari popülasyon değeri
2. Göç etme nedenlerine göre illerin aldığı göç miktarı
3. Göç etme nedenlerine göre illerin verdiği göç miktarı
4. Göç etme nedenlerine göre illerin net göç miktarı


## 2.1 Data Source

xxxxxx

## 2.2 General Information About Data

xxxxxx

## 2.3 Reason of Choice

xxxxxx

## 2.4 Preprocessing

#Farklı excel verilerinde yer alan İllerin aldığı ve Verdiği Göç Değerlerinden Net Göç Hesaplanması ve verilerdeki char formatında yazılan boşluklu değerlerin numaric değerler olarak güncellenmesi işlemleri uygulanmıştır.

    
#install.packages("ggplot2") 
#install.packages("dplyr")   
#install.packages("openxlsx")
library(ggplot2)
library(dplyr)
library(readxl) 
library(writexl) 
library(stringr)
library(forcats)
library(tidyr)
library(openxlsx)


# Net göç bilgisi hesaplama ve excel dosyası oluşturma

VerilenGoc <- read_excel("C:/EMU660_Project/emu660-spring2026-Selindznn/VerilenGoc.xlsx", col_names = TRUE)
AlinanGoc  <- read_excel("C:/EMU660_Project/emu660-spring2026-Selindznn/AlinanGoc.xlsx", col_names = TRUE)
toplam_sutun <- ncol(VerilenGoc)
fark_df <- VerilenGoc 
for (i in 3:toplam_sutun) {
  v_clean <- as.character(VerilenGoc[[i]])
  v_clean <- str_replace_all(v_clean, "\\s", "") 
  VerilenGoc[[i]] <- as.numeric(v_clean)        
  a_clean <- as.character(AlinanGoc[[i]])
  a_clean <- str_replace_all(a_clean, "\\s", "")    
  AlinanGoc[[i]] <- as.numeric(a_clean)
}
fark_df[, 3:toplam_sutun] <- VerilenGoc[, 3:toplam_sutun] - AlinanGoc[, 3:toplam_sutun]
for (i in 3:toplam_sutun) {
  fark_df[[i]] <- as.numeric(fark_df[[i]])
}
write_xlsx(fark_df, "C:/EMU660_Project/emu660-spring2026-Selindznn/NetGoc.xlsx")

print(VerilenGoc[, 3:toplam_sutun])

# İllerin populasyon verisi ile Net göç hızı hesaplama ve excel dosyası oluşturma

kaynak_yolu <- "C:/EMU660_Project/emu660-spring2026-Selindznn/NetGoc.xlsx"
hedef_yolu  <- "C:/EMU660_Project/emu660-spring2026-Selindznn/IlNufuslarii.xlsx"

df_kaynak <- read_excel(kaynak_yolu, col_names = TRUE)

NetGocVerisi <- df_kaynak[1:82, 3, drop = TRUE] 

wb <- loadWorkbook(hedef_yolu)

writeData(wb, sheet = 1, x = "Net Göç", startCol = 3, startRow = 1, colNames = FALSE)
writeData(wb, sheet = 1, x = NetGocVerisi, startCol = 3, startRow = 2, colNames = FALSE)

saveWorkbook(wb, hedef_yolu, overwrite = TRUE)

# 3. Analysis

## 3.1 Exploratory Data Analysis

# Yıllara göre Toplam Verilen Göç Miktarı Değişimi
grafik_verisi <- VerilenGoc[VerilenGoc[, 2] == "Toplam-Total", ]
print(grafik_verisi)
head(grafik_verisi)

yil <- factor(grafik_verisi[[1]], levels = sort(unique(grafik_verisi[[1]]), decreasing = TRUE))
goc_miktari  <- as.numeric(grafik_verisi[[3]])/1000  

ggplot(data = grafik_verisi, aes(x = yil, y = goc_miktari)) +
  geom_col(fill = "steelblue", alpha = 0.7) + 
  geom_line(color = "black", size = 2) + 
  geom_point(color = "darkred", size = 3) +
  geom_text(aes(label = round(goc_miktari, 1)), vjust = -0.5, size = 3.5) +
  labs(
    title = "Yıllara Göre Toplam Verilen Göç Miktarı",
    x = "Yıl",
    y = "Göç Miktarı (x1.000)"
  )
  
  
# Ankara için Yıllara Göre Toplam Verilen Göç Miktarı
grafik_verisi <- VerilenGoc[VerilenGoc[, 2] == "Ankara", ]
print(grafik_verisi)
head(grafik_verisi)

yil <- factor(grafik_verisi[[1]], levels = sort(unique(grafik_verisi[[1]]), decreasing = TRUE))
goc_miktari  <- as.numeric(grafik_verisi[[3]])/1000  

ggplot(data = grafik_verisi, aes(x = yil, y = goc_miktari)) +
  geom_col(fill = "steelblue", alpha = 0.7) + 
  geom_line(color = "black", size = 2) + 
  geom_point(color = "darkred", size = 3) +
  geom_text(aes(label = round(goc_miktari, 1)), vjust = -0.5, size = 3.5) +
  labs(
    title = "Ankara için Yıllara Göre Toplam Verilen Göç Miktarı",
    x = "Yıl",
    y = "Göç Miktarı (x1.000)"
  )
  

# 2024 yılı İllerin Alınan Göç Miktarları
AlinanGoc  <- read_excel("C:/EMU660_Project/emu660-spring2026-Selindznn/AlinanGoc.xlsx",col_names = TRUE)

colnames(AlinanGoc)[1:3] <- c("Yil", "Il", "Goc_Miktari")
veri_2024 <- subset(AlinanGoc, Yil == 2024 & Il != "Toplam-Total")
veri_2024$Goc_Miktari_Bin <- veri_2024$Goc_Miktari / 1000


ggplot(veri_2024, aes(x = Goc_Miktari_Bin, y = reorder(Il, Goc_Miktari_Bin))) +
  geom_col(aes(fill = Goc_Miktari_Bin > 0)) +
  scale_fill_manual(values = c("coral", "skyblue"), guide = "none") +
  theme_minimal() +
  labs(
    title = "2024 Yılı İllerin Alınan Göç Miktarları",
    x = "Alınan Göç Miktarı (Bin Kişi)",
    y = "İller"
  )
  
# 2024 yılı İllerin net Göç Miktarları
NetGoc  <- read_excel("C:/EMU660_Project/emu660-spring2026-Selindznn/NetGoc.xlsx",col_names = TRUE)

colnames(NetGoc)[1:3] <- c("Yil", "Il", "Goc_Miktari")
veri_2024 <- subset(NetGoc, Yil == 2024 & Il != "Toplam-Total")
veri_2024$Goc_Miktari_Bin <- veri_2024$Goc_Miktari / 1000


ggplot(veri_2024, aes(x = Goc_Miktari_Bin, y = reorder(Il, Goc_Miktari_Bin))) +
  geom_col(aes(fill = Goc_Miktari_Bin > 0)) +
  scale_fill_manual(values = c("coral", "skyblue"), guide = "none") +
  theme_minimal() +
  labs(
    title = "2024 Yılı İllerin NEt Göç Miktarları",
    x = "Net Göç Miktarı (Bin Kişi)",
    y = "İller"
  )  
  
# göç nedenleri stacked halde gösterme

NetGoc  <- read_excel("C:/EMU660_Project/emu660-spring2026-Selindznn/NetGoc.xlsx",col_names = TRUE)

goc_nedenleri <- c("Tayin/Is Degisikligi", "Ise Baslamak/Is Bulmak", "Egitim", 
                   "Medeni Durum/Ailevi", "Daha Iyi Konut/Yasam", "Haneye Bagimli Goc", 
                   "Memlekete Donus", "Saglik/Bakim", "Ev Alinmasi", 
                   "Emeklilik", "Diger", "Bilinmeyen")

colnames(NetGoc)[1:3] <- c("Yil", "Il", "Toplam_Goc")
colnames(NetGoc)[4:15] <- goc_nedenleri
veri_2024 <- subset(NetGoc, Yil == 2024 & Il != "Toplam-Total")

veri_uzun <- pivot_longer(veri_2024, 
                          cols = 4:15, 
                          names_to = "Goc_Nedeni", 
                          values_to = "Miktar")

veri_uzun$Miktar_Bin <- veri_uzun$Miktar / 1000

goc_grafigi <- ggplot(veri_uzun, aes(x = Miktar_Bin, y = reorder(Il, Toplam_Goc), fill = Goc_Nedeni)) +
  geom_col(position = "stack") +
  theme_minimal() +
  labs(
    title = "2024 Yılı İllerin Göç Nedenlerine Göre Dağılımı",
    subtitle = "Miktarlar bin kişi cinsinden ifade edilmiştir",
    x = "Net Göç Miktarı (Bin Kişi)",
    y = "İller",
    fill = "Göç Nedenleri"
  ) +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 8),
    axis.text.y = element_text(size = 7)
  ) +
  guides(fill = guide_legend(ncol = 3))
  
print(goc_grafigi)


## 3.2 Trend Analysis

#install.packages("ggrepel")
library(ggplot2)
library(readxl)
library(dplyr)
library(ggrepel) # Etiketlerin üst üste binmesini önlemek için

yasam_df <- read_excel("C:/EMU660_Project/emu660-spring2026-Selindznn/YasamEndeksi.xlsx", col_names = TRUE)
goc_df <- read_excel("C:/EMU660_Project/emu660-spring2026-Selindznn/Gochizi.xlsx", col_names = TRUE)

colnames(yasam_df)[1:2] <- c("Il", "Endeks")
colnames(goc_df)[1:3]   <- c("Yil", "Il", "Goc")

goc_2024 <- subset(goc_df, Yil == 2024 & Il != "Toplam-Total")

veri_seti <- inner_join(yasam_df, goc_2024, by = "Il")

grafik <- ggplot(veri_seti, aes(x = Endeks, y = Goc, label = Il)) + # label = Il eklendi
  geom_point(color = "#1f77b4", size = 3, alpha = 0.7) + 
  geom_text_repel(size = 3, max.overlaps = 15) + # Noktaların üzerine il isimlerini akıllıca yerleştirir
  geom_smooth(method = "lm", color = "red", se = TRUE, formula = y ~ x) + 
  labs(
    title = "İl Yaşam Endeksi ve 2024 Net Göç Hızı İlişkisi",
    x = "Genel Yaşam Endeksi",
    y = "Net Göç Hızı (‰)"
  ) +
  theme_minimal()

print(grafik)

## 3.4 Results

xxxxxx

# 4. Results and Key Takeaways

xxxxxx
